# Generated by Django 5.1.1 on 2026-03-20 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Seri No')),
                ('location', models.TextField(verbose_name='Konum')),
                ('install_date', models.DateField(verbose_name='Kurulum Tarihi')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Son Bakım')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('fault', 'Arızalı')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=30, unique=True, verbose_name='Parça Kodu')),
                ('name', models.CharField(max_length=100, verbose_name='Parça Adı')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Stok')),
                ('min_stock', models.PositiveIntegerField(default=5, verbose_name='Kritik Seviye')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Barkod')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('periodic', 'Periyodik'), ('fault', 'Arıza')], max_length=20, verbose_name='İş Türü')),
                ('due_date', models.DateField(verbose_name='Tahmini Tarih')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('completed', 'Tamamlandı')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Atanan')),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.elevator', verbose_name='Asansör')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('transaction_type', models.CharField(choices=[('in', 'Giriş'), ('out', 'Çıkış')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.sparepart')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='elevator.maintenancetask')),
            ],
        ),
    ]
