# Generated by Django 5.1.1 on 2026-03-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancetask',
            options={'ordering': ['start_datetime', 'due_date']},
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Saati'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Saati'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='due_date',
            field=models.DateField(verbose_name='Tarih'),
        ),
    ]
