# Generated by Django 5.1.1 on 2026-03-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0002_alter_maintenancetask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='Bütün Gün (All Day)'),
        ),
    ]
