# Generated by Django 5.1.1 on 2026-03-24 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_maintenancetask_all_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('company', models.CharField(blank=True, max_length=150, null=True, verbose_name='Firma')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-posta')),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram ID')),
                ('preferred_channel', models.CharField(choices=[('email', 'E-posta'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Telefon Araması')], default='whatsapp', max_length=20, verbose_name='Tercih Edilen Kanal')),
                ('notes', models.TextField(blank=True, verbose_name='Notlar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='elevator',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elevator.customer', verbose_name='Müşteri'),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'E-posta'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Telefon Araması')], max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Başarılı'), ('failed', 'Başarısız')], default='success', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator.customer')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='elevator.maintenancetask')),
            ],
            options={
                'verbose_name': 'Bildirim Logu',
                'verbose_name_plural': 'Bildirim Logları',
                'ordering': ['-sent_at'],
            },
        ),
    ]
