# Generated by Django 5.1.1 on 2026-03-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0004_customer_elevator_customer_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tarih (Opsiyonel)'),
        ),
    ]
