# Generated by Django 5.1.1 on 2026-03-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0005_alter_maintenancetask_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Bildirim Gönderildi mi?'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='all_day',
            field=models.BooleanField(default=False, verbose_name='Bütün Gün'),
        ),
    ]
