# Generated by Django 5.1.1 on 2026-03-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0006_maintenancetask_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notlar'),
        ),
        migrations.DeleteModel(
            name='StockTransaction',
        ),
    ]
