# Generated by Django 5.1.1 on 2026-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0007_elevator_notes_delete_stocktransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Okundu mu?'),
        ),
    ]
