# Generated by Django 5.1.1 on 2026-03-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('elevator', '0008_notificationlog_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('task_reminder', 'Yaklaşan Görev'), ('critical_stock', 'Kritik Stok')], default='task_reminder', max_length=30),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(blank=True, choices=[('email', 'E-posta'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Telefon Araması')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elevator.customer'),
        ),
    ]
